#' create_raw
#' @name create_raw
#' @param start_date Character string to tell Qualtrics to pull data from this date
#' @description A wraper for the fetch_survey function from qualtRics
#'
#' @return The return value, if any, from executing the utility.
#'
#' @export

create_raw <- function(start_date){
  qualtRics::fetch_survey("SV_8eV8SVyYthinWZM",
                          start_date = start_date,
                          force_request = TRUE)
}




#' create_program
#' @description initial clean upof data set from create_raw
#' @param df output from read_raw
#' @return a data frame
#' @export
#'

create_program <- function(df){
  df %>%
    janitor::clean_names() %>%
    #dplyr::select(-all_of(remove_v)) %>%
    dplyr::mutate(girl_code = stringr::str_to_upper(girl_code)) %>%
    dplyr::mutate(recorded_date=lubridate::as_date(recorded_date)) %>%
    dplyr::filter(!is.na(girl_code)) %>%
    dplyr::filter(!is.na(grant))  %>%
    dplyr::mutate(grant = as.character.factor(grant)) %>%
    dplyr::mutate(time = as.character.factor(time))

  #df$girl_code <- toupper(df$girl_code)



}


#' create_program_dat
#' @description  create data frame with just pre surveys and wipe out duplicate girl_codes from df
#' @param df that data frame that is used.
#' @param time consists of pre/post.
#'
#' @return a data frame with just pre surveys
#' @export
#'

create_program_dat <- function(df, time){
  df %>%
    dplyr::filter(time == {{time}}) %>%
    dplyr::distinct(girl_code, .keep_all = TRUE)

}


#' create_level_results
#'
#' @description  takes input from the result of create pre_program_dat and returns outcome by levels
#' @param df the current data frame used is 'program_data_21'
#'
#' @return a date frame
#' @export
#'

create_level_results <- function(df){

  level_results <- gswcf::outcome_result(df)
  level_results$result <- tidyr::replace_na(level_results$result, "DQ")
  level_results$result <- forcats::fct_relevel(level_results$result, "High", "Medium", "Low", "DQ")
  level_results
}

#' create_stats
#'
#' @description  function to get numeric variables and stats from pre survey
#'
#' @param df the current data frame used is 'program_data_21'
#'
#' @return
#' @export
#'


# WARNING - Generated by {fusen} from /dev/flat_additional.Rmd: do not edit by hand

#' create levels
#'
#' A function to  reshape data set for display and analysis
#' @param df a data frame
#' @return a data frame
#'
#' @export
#' @examples
#' df_1 <- create_levels(df)
create_levels <- function(df){
  df %>%
    dplyr::select(grant,time, girl_code, site, gs_level, contains("score")) %>%
    tidyr::pivot_longer(
      cols = contains("score"),
      names_to = "outcomes",
      values_to = "result"
    ) %>%
    transform(outcomes = dplyr::case_when(
      outcomes == "challenge_seeking_score" ~ "Challenge Seeking",
      outcomes == "community_problem_solving_score" ~ "Community Problem Solving",
      outcomes == "healthy_relationships_score" ~ "Healthy Relationships",
      outcomes == "positive_values_score" ~ "Positive Values",
      outcomes == "sense_of_self_score" ~ "Sense of Self",
      outcomes == "girl_led_score" ~ "Girl Led",
      outcomes == "cooperative_learning_score" ~ "Cooperative Learning",
      outcomes == "learning_by_doing_score" ~ "Learning by Doing"

    )) %>%
    #pre_outcomes$result <- tidyr::replace_na(pre_outcomes$result, "DQ")
    #pre_outcomes$result <- fct_relevel(pre_outcomes$result, "High", "Medium", "Low", "DQ")
    tidyr::replace_na(list(result= "DQ"))   %>%
    dplyr::mutate(result = forcats::fct_relevel(
      result, c("High", "Medium", "Low", "DQ")))



}






create_stats <- function(df){
  stats <- gswcf::outcome_summary_dat(df)

}


# WARNING - Generated by {fusen} from /dev/flat_additional.Rmd: do not edit by hand

#' create summary
#'
#' @description selects and summarizes mean scores and display in df.
#'
#' @param  df a data frame
#' @return df
#'
#' @export
#' @examples
#'  create_summary(df)
create_summary <- function(df){
  df %>%
    dplyr::select(girl_code, grant, time, site, contains("mean"))%>%
    dplyr::select(-5,-6,-15,-16,-18,-19,-20,-21,-22) %>%
    dplyr::mutate(across(contains("mean"),as.numeric))


}

#' create process summary
#'
#' @description selects and summarizes mean scores and display in df.
#'
#' @param  df a data frame
#' @return df
#'
#' @export
#' @examples
#'  create_summary(df)
create_process_summary <- function(df){
  df %>%
    dplyr::select(girl_code, grant, time, site, contains("mean"))%>%
    dplyr::select(girl_code, grant, time, site, girl_led_mean, cooperative_learning_mean, learning_by_doing_action_mean, learning_by_doing_reflection_mean, learning_by_doing_mean ) %>%
    dplyr::mutate(across(contains("mean"),as.numeric))


}
